addSbtPlugin("com.dwijnand" % "sbt-travisci" % "1.2.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.2.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.3.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.9")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.1")
addSbtPlugin("org.tpolecat" % "tut-plugin" % "0.6.13")
